[project]
name = "correo-nood-a-pro"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "jinja2>=3.1.6",
    "mjml>=0.11.0",
    "mjml-python>=1.3.5",
]
